(function(){
    function renderTrainerCard(a, c) {
        var t=a.trainer;if(!t)return;var d=document.createElement('div');d.className='vit-card p-0 mb-3';
        d.style.cssText='border:1px solid #fed7aa;overflow:hidden;';d.id='trainerCard_'+a.id;
        d.innerHTML='<div style="padding:12px 16px;background:linear-gradient(135deg,rgba(239,125,0,0.08),rgba(245,158,11,0.04));border-bottom:1px solid #fed7aa;"><div class="flex items-center justify-between"><div class="flex items-center gap-2"><span style="font-size:18px">🎓</span><div><p class="text-[10px] font-bold text-vit-orange uppercase">'+(t.area_key||'').toUpperCase()+'</p><p class="text-sm font-bold text-gray-800">'+t.title+'</p></div></div><span class="text-[10px] text-gray-400">'+(t.duration_minutes||5)+' Min</span></div></div><div style="padding:12px 16px;"><p class="text-xs text-gray-600 mb-2">'+(t.summary||'')+'</p><div class="flex gap-2"><button onclick="window._startDbTrainer&&window._startDbTrainer(\''+a.id+'\')" class="flex-1 px-3 py-2 bg-vit-orange text-white text-xs font-bold rounded-lg hover:opacity-90">▶ Starten</button><button onclick="window._snoozeDbTrainer&&window._snoozeDbTrainer(\''+a.id+'\')" class="px-3 py-2 bg-gray-100 text-gray-500 text-xs font-bold rounded-lg hover:bg-gray-200">⏰ Später</button></div></div>';
        c.appendChild(d);
    }
    async function loadTrainersForArea(k){if(typeof sb==='undefined'||!sbProfile)return[];try{var r=await sb.from('trainer_assignments').select('*,trainer:trainer_id(*)').eq('standort_id',sbProfile.standort_id).eq('status','active');return(r.data||[]).filter(function(a){return a.trainer&&a.trainer.is_active&&(!k||a.trainer.area_key===k)&&(!a.cooldown_until||new Date(a.cooldown_until)<=new Date());}).sort(function(a,b){return(a.trainer.priority||3)-(b.trainer.priority||3);}).slice(0,1);}catch(e){return[];}}
    async function _smartTriggerCheck(k){if(typeof sb==='undefined'||!sbProfile||!sbProfile.standort_id)return;var sid=sbProfile.standort_id;try{var t=(await sb.from('trainers').select('*').eq('area_key',k).eq('is_active',true)).data||[];if(!t.length)return;var ex=((await sb.from('trainer_assignments').select('trainer_id').eq('standort_id',sid).eq('status','active')).data||[]).map(function(a){return a.trainer_id;});var cm={};((await sb.from('trainer_completions').select('trainer_id,completed_at').eq('standort_id',sid).order('completed_at',{ascending:false}).limit(50)).data||[]).forEach(function(c){cm[c.trainer_id]=c.completed_at;});for(var i=0;i<t.length;i++){var tr=t[i];if(ex.indexOf(tr.id)>=0)continue;if(cm[tr.id]&&(Date.now()-new Date(cm[tr.id]).getTime())/86400000<14)continue;var fire=await _evaluateTrigger(tr,sid);if(fire)await sb.from('trainer_assignments').upsert({trainer_id:tr.id,standort_id:sid,status:'active'},{onConflict:'trainer_id,standort_id'});}}catch(e){console.warn('SmartTrigger:',e);}}
    async function _evaluateTrigger(tr,sid){var k=tr.trigger_key;if(k==='open_offers_no_followup'){var r=await sb.from('leads').select('id,letzter_kontakt,status').eq('standort_id',sid).not('status','in','("gewonnen","verloren")');var l=r.data||[];return l.filter(function(x){return!x.letzter_kontakt||(Date.now()-new Date(x.letzter_kontakt).getTime())/86400000>7;}).length>=5||l.length===0;}if(k==='bwa_missing'){var m=typeof getBwaMonth==='function'?getBwaMonth(new Date()):null;if(!m)return false;var r=await sb.from('bwa_daten').select('id').eq('standort_id',sid).eq('monat',m.m+1).eq('jahr',m.y).limit(1);return!(r.data&&r.data.length>0);}if(k==='no_content_14d'){var s=new Date(Date.now()-14*86400000).toISOString();var r=await sb.from('portal_events').select('id').eq('standort_id',sid).eq('event_type','content_uploaded').gte('created_at',s).limit(1);return!(r.data&&r.data.length>0);}return false;}
    window.showTrainerForArea=async function(k,cid){var c=document.getElementById(cid);if(!c)return;c.innerHTML='';await _smartTriggerCheck(k);var a=await loadTrainersForArea(k);if(a.length>0)renderTrainerCard(a[0],c);};
    window._snoozeDbTrainer=async function(id){if(typeof sb==='undefined')return;await sb.from('trainer_assignments').update({cooldown_until:new Date(Date.now()+48*3600000).toISOString()}).eq('id',id);var c=document.getElementById('trainerCard_'+id);if(c)c.remove();};
    window._startDbTrainer=function(){alert(t('tr_started'));};
})();
